"""Storage adapter protocol."""
from __future__ import annotations

from typing import Protocol

from models import PostBrief, Status


class StorageAdapter(Protocol):
    def write(self, brief: PostBrief) -> None: ...
    def read(self, slug: str) -> PostBrief: ...
    def list_slugs(self) -> list[str]: ...
    def update_status(self, slug: str, new_status: Status, actor: str = "user") -> PostBrief: ...
    def delete(self, slug: str) -> None: ...
